url: https://larsjx.github.io
baseurl:

# Site settings
title: Lars Johnson
email: your-email@domain.com
description: "Lars Johnson's Website"

# Color settings (hex-codes without the leading hash-tag - fed136, fec503)
color:
  primary: 09155C               #09155C #163497 (not working)
  secondary: white              #white 09155C  FFD00D
  secondary-dark: black         #333

# Team names, titles and social links
people:
- name: IBM Headquarters Staff
  pic: 3
  position: Global Client Satisfaction and Sales Ops
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: IBM Internet Solutions
  pic: 2
  position: Technical Sales Management
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Enterprise Software
  pic: 1
  position: Software Sales
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/larsjx
  - title: facebook
    url: https://www.facebook.com/larsjx
  - title: linkedin
    url: https://www.linkedin.com/in/larsjx
  - title: github
    url: http://github.com/larsjx


# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
# markdown: kramdown
# permalink: pretty
permalink: none
future: true